sudo: required
services:
  - docker


before_install:
  - docker build -f ./client/Dockerfile.dev -t chinmaya/client-react ./client

script:
  - docker run chinmaya/client-react npm run test -- --coverage
  
after_success:
  - docker build -t chinmayapalo/multi-client ./client
  - docker build -t chinmayapalo/multi-nginx ./nginx
  - docker build -t chinmayapalo/multi-server ./server
  - docker build -t chinmayapalo/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push chinmayapalo/multi-client
  - docker push chinmayapalo/multi-nginx
  - docker push chinmayapalo/multi-server
  - docker push chinmayapalo/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-south-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-ap-south-1-159145277228"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $Access_key_ID
#   secret_access_key:
#     secure: "$Secret_access_key"