version: '3'
services:
  postgres:
    image: 'postgres:latest' 
  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    image: 'checkpoint-nginx:latest'
    ports:
      - '3050:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    image: 'checkpoint-server:latest'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    image: 'checkpoint-client:latest'
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    image: 'checkpoint-worker:latest'
    volumes:
      - /app/node_modules
      - ./worker:/app
    
      
    